HERO_ID_MAP = {
    "anti-mage": 1,
    "axe": 2,
    "bane": 3,
    "bloodseeker": 4,
    "crystal maiden": 5,
    "drow ranger": 6,
    "earthshaker": 7,
    "juggernaut": 8,
    "mirana": 9,
    "morphling": 10,
    "shadow fiend": 11,
    "phantom lancer": 12,
    "puck": 13,
    "pudge": 14,
    "razor": 15,
    "sand king": 16,
    "storm spirit": 17,
    "sven": 18,
    "tiny": 19,
    "vengeful spirit": 20,
    "windranger": 21,
    "zeus": 22,
    "kunkka": 23,
    "lina": 25,
    "lion": 26,
    "shadow shaman": 27,
    "slardar": 28,
    "tidehunter": 29,
    "witch doctor": 30,
    "lich": 31,
    "riki": 32,
    "enigma": 33,
    "tinker": 34,
    "sniper": 35,
    "necrophos": 36,
    "warlock": 37,
    "beastmaster": 38,
    "queen of pain": 39,
    "venomancer": 40,
    "faceless void": 41,
    "wraith king": 42,
    "death prophet": 43,
    "phantom assassin": 44,
    "pugna": 45,
    "templar assassin": 46,
    "viper": 47,
    "luna": 48,
    "dragon knight": 49,
    "dazzle": 50,
    "clockwerk": 51,
    "leshrac": 52,
    "nature's prophet": 53,
    "lifestealer": 54,
    "dark seer": 55,
    "clinkz": 56,
    "omniknight": 57,
    "enchantress": 58,
    "huskar": 59,
    "night stalker": 60,
    "broodmother": 61,
    "bounty hunter": 62,
    "weaver": 63,
    "jakiro": 64,
    "batrider": 65,
    "chen": 66,
    "spectre": 67,
    "ancient apparition": 68,
    "doom": 69,
    "ursa": 70,
    "spirit breaker": 71,
    "gyrocopter": 72,
    "alchemist": 73,
    "invoker": 74,
    "silencer": 75,
    "outworld destroyer": 76,
    "lycan": 77,
    "brewmaster": 78,
    "shadow demon": 79,
    "lone druid": 80,
    "chaos knight": 81,
    "meepo": 82,
    "treant protector": 83,
    "ogre magi": 84,
    "undying": 85,
    "rubick": 86,
    "disruptor": 87,
    "nyx assassin": 88,
    "naga siren": 89,
    "keeper of the light": 90,
    "io": 91,
    "visage": 92,
    "slark": 93,
    "medusa": 94,
    "troll warlord": 95,
    "centaur warrunner": 96,
    "magnus": 97,
    "timbersaw": 98,
    "bristleback": 99,
    "tusk": 100,
    "skywrath mage": 101,
    "abaddon": 102,
    "elder titan": 103,
    "legion commander": 104,
    "techies": 105,
    "ember spirit": 106,
    "earth spirit": 107,
    "underlord": 108,
    "terrorblade": 109,
    "phoenix": 110,
    "oracle": 111,
    "winter wyvern": 112,
    "arc warden": 113,
    "monkey king": 114,
    "dark willow": 119,
    "pangolier": 120,
    "grimstroke": 121,
    "hoodwink": 123,
    "void spirit": 126,
    "snapfire": 128,
    "mars": 129,
    "ringmaster": 131,
    "dawnbreaker": 135,
    "marci": 136,
    "primal beast": 137,
    "muerta": 138,
    "kez": 145,
    "largo": 155
}

ID_HERO_MAP = {v: k for k, v in HERO_ID_MAP.items()}