import requests
import json

token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJodHRwczovL3N0ZWFtY29tbXVuaXR5LmNvbS9vcGVuaWQvaWQvNzY1NjExOTgxMzM5NjA1MjUiLCJ1bmlxdWVfbmFtZSI6InJlcG9ydCAgdGVjaCIsIlN1YmplY3QiOiI5NzExMzlhNy03NDFmLTQ0MDYtODU4Yy0zMzQxNjA2Yzc0YmQiLCJTdGVhbUlkIjoiMTczNjk0Nzk3IiwibmJmIjoxNjUyODI5OTkwLCJleHAiOjE2ODQzNjU5OTAsImlhdCI6MTY1MjgyOTk5MCwiaXNzIjoiaHR0cHM6Ly9hcGkuc3RyYXR6LmNvbSJ9.quV4xwb4_ko9JSCfi85v5KiHzosnOY4EfXV7kk-I5UE'

headers = {'Authorization': 'Bearer {}' .format(token)}
# r= requests.get('https://api.stratz.com/api/v1/Hero?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJodHRwczovL3N0ZWFtY29tbXVuaXR5LmNvbS9vcGVuaWQvaWQvNzY1NjExOTgxMzM5NjA1MjUiLCJ1bmlxdWVfbmFtZSI6InJlcG9ydCAgdGVjaCIsIlN1YmplY3QiOiI5NzExMzlhNy03NDFmLTQ0MDYtODU4Yy0zMzQxNjA2Yzc0YmQiLCJTdGVhbUlkIjoiMTczNjk0Nzk3IiwibmJmIjoxNjUyODI5OTkwLCJleHAiOjE2ODQzNjU5OTAsImlhdCI6MTY1MjgyOTk5MCwiaXNzIjoiaHR0cHM6Ly9hcGkuc3RyYXR6LmNvbSJ9.quV4xwb4_ko9JSCfi85v5KiHzosnOY4EfXV7kk-I5UE', headers=headers)
#
# res = [ele['shortName'] for ele in dict(r.json()).values()]
# print(res)

startz_hero_list = ['antimage', 'axe', 'bane', 'bloodseeker', 'crystal_maiden', 'drow_ranger', 'earthshaker', 'juggernaut', 'mirana', 'morphling', 'nevermore', 'phantom_lancer', 'puck', 'pudge', 'razor', 'sand_king', 'storm_spirit', 'sven', 'tiny', 'vengefulspirit', 'windrunner', 'zuus', 'kunkka', 'lina', 'lion', 'shadow_shaman', 'slardar', 'tidehunter', 'witch_doctor', 'lich', 'riki', 'enigma', 'tinker', 'sniper', 'necrolyte', 'warlock', 'beastmaster', 'queenofpain', 'venomancer', 'faceless_void', 'skeleton_king', 'death_prophet', 'phantom_assassin', 'pugna', 'templar_assassin', 'viper', 'luna', 'dragon_knight', 'dazzle', 'rattletrap', 'leshrac', 'furion', 'life_stealer', 'dark_seer', 'clinkz', 'omniknight', 'enchantress', 'huskar', 'night_stalker', 'broodmother', 'bounty_hunter', 'weaver', 'jakiro', 'batrider', 'chen', 'spectre', 'ancient_apparition', 'doom_bringer', 'ursa', 'spirit_breaker', 'gyrocopter', 'alchemist', 'invoker', 'silencer', 'obsidian_destroyer', 'lycan', 'brewmaster', 'shadow_demon', 'lone_druid', 'chaos_knight', 'meepo', 'treant', 'ogre_magi', 'undying', 'rubick', 'disruptor', 'nyx_assassin', 'naga_siren', 'keeper_of_the_light', 'wisp', 'visage', 'slark', 'medusa', 'troll_warlord', 'centaur', 'magnataur', 'shredder', 'bristleback', 'tusk', 'skywrath_mage', 'abaddon', 'elder_titan', 'legion_commander', 'techies', 'ember_spirit', 'earth_spirit', 'abyssal_underlord', 'terrorblade', 'phoenix', 'oracle', 'winter_wyvern', 'arc_warden', 'monkey_king', 'dark_willow', 'pangolier', 'grimstroke', 'hoodwink', 'void_spirit', 'snapfire', 'mars', 'dawnbreaker', 'marci', 'primal_beast']

r= requests.get('https://api.stratz.com/api/v1/Hero/1/highPerformance?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJodHRwczovL3N0ZWFtY29tbXVuaXR5LmNvbS9vcGVuaWQvaWQvNzY1NjExOTgxMzM5NjA1MjUiLCJ1bmlxdWVfbmFtZSI6InJlcG9ydCAgdGVjaCIsIlN1YmplY3QiOiI5NzExMzlhNy03NDFmLTQ0MDYtODU4Yy0zMzQxNjA2Yzc0YmQiLCJTdGVhbUlkIjoiMTczNjk0Nzk3IiwibmJmIjoxNjUyODI5OTkwLCJleHAiOjE2ODQzNjU5OTAsImlhdCI6MTY1MjgyOTk5MCwiaXNzIjoiaHR0cHM6Ly9hcGkuc3RyYXR6LmNvbSJ9.quV4xwb4_ko9JSCfi85v5KiHzosnOY4EfXV7kk-I5UE', headers=headers)
print(startz_hero_list.index('zeus'))